#!/usr/bin/env python3

import os
import sys
from argparse import ArgumentParser
from subprocess import call


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument('example', nargs='+')
    example_group = parser.add_argument_group(
        'examples')
    example_group.add_argument('http', action='store_true')
    example_group.add_argument('socket', action='store_true')
    example_group.add_argument('performance', action='store_true')
    args = parser.parse_args()

    script_path = os.path.dirname(os.path.realpath(__file__))
    build_path = os.path.join(script_path, 'build')

    for example in args.example:
        bin = os.path.join(build_path,
                           'examples',
                           example,
                           'example_' + example)
        call([bin])
