#!/bin/sh -e

# Defining to script path.
SCRIPTPATH="$(readlink -f $(dirname $0))"

# Preparing the build.
"$SCRIPTPATH/prepare"

# Uncrustifying all source files.
type uncrustify > /dev/null && for FILE in $(find "$SCRIPTPATH/src" "$SCRIPTPATH/unittest" -name *.cpp -o -name *.hpp); do
    uncrustify --replace --no-backup -c "$SCRIPTPATH/uncrustify.cfg" -l CPP $FILE
done

# Doing cppcheck.
cd "$SCRIPTPATH/build"
make check
