#!/bin/sh

# Jump to script path.
SCRIPTPATH="$(readlink -f $(dirname $0))"

# Preparing the build.
"$SCRIPTPATH/prepare"

# Making the build.
cd "$SCRIPTPATH/build" && make -j"$(grep processor /proc/cpuinfo | wc -l)"

# Executing the tests.
LD_LIBRARY_PATH="$SCRIPTPATH/build/src" "$SCRIPTPATH/build/unittest/unittest_rest"
